# Generated by Django 4.2.7 on 2025-11-28 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogos',
            fields=[
                ('id_catalogo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_catalogo', models.CharField(max_length=50)),
                ('clave', models.CharField(max_length=20)),
                ('valor', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'catalogos',
            },
        ),
        migrations.CreateModel(
            name='Coberturas',
            fields=[
                ('id_cobertura', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_cobertura', models.CharField(max_length=50)),
                ('monto_poliza', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'coberturas',
            },
        ),
        migrations.CreateModel(
            name='Contratos',
            fields=[
                ('id_contrato', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('renta_mensual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('iva_incluido', models.BooleanField(default=False)),
                ('mas_iva', models.BooleanField(default=False)),
                ('mantenimiento_incluido', models.BooleanField(default=False)),
                ('mantenimiento_adicional', models.BooleanField(default=False)),
                ('monto_adicional', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deposito_garantia', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lugares_estacionamiento', models.IntegerField(blank=True, null=True)),
                ('mascotas', models.TextField(blank=True, null=True)),
                ('inventario', models.TextField(blank=True, null=True)),
                ('servicios', models.TextField(blank=True, null=True)),
                ('pago_poliza_arrendador', models.BooleanField(default=False)),
                ('pago_poliza_arrendatario', models.BooleanField(default=False)),
                ('porcentaje_poliza', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('acepto_terminos', models.BooleanField(default=False)),
                ('motivos_cambio', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contratos',
            },
        ),
        migrations.CreateModel(
            name='Domicilios',
            fields=[
                ('id_domicilio', models.AutoField(primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=100)),
                ('no_exterior', models.CharField(blank=True, max_length=10, null=True)),
                ('no_interior', models.CharField(blank=True, max_length=10, null=True)),
                ('edificio', models.CharField(blank=True, max_length=50, null=True)),
                ('cp', models.CharField(max_length=10)),
                ('colonia', models.CharField(max_length=100)),
                ('alcaldia_municipio', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'domicilios',
            },
        ),
        migrations.CreateModel(
            name='Inmuebles',
            fields=[
                ('id_inmueble', models.AutoField(primary_key=True, serialize=False)),
                ('giro_negocio', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_domicilio', models.ForeignKey(db_column='id_domicilio', on_delete=django.db.models.deletion.CASCADE, to='api.domicilios')),
            ],
            options={
                'db_table': 'inmuebles',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('permisos_json', models.JSONField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='UsuariosInternos',
            fields=[
                ('id_usuario_interno', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('ultimo_login', models.DateTimeField(blank=True, null=True)),
                ('fecha_bloqueo', models.DateTimeField(blank=True, null=True)),
                ('intentos_fallidos', models.IntegerField(default=0)),
                ('id_rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.CASCADE, to='api.roles')),
            ],
            options={
                'db_table': 'usuarios_internos',
            },
        ),
        migrations.CreateModel(
            name='ReferenciasPersonales',
            fields=[
                ('id_referencia', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_referencia', models.CharField(choices=[('PERSONAL', 'Personal'), ('LABORAL', 'Laboral'), ('ARRENDADOR_ANTERIOR', 'Arrendador Anterior')], max_length=20)),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('relacion', models.CharField(blank=True, max_length=100, null=True)),
                ('domicilio', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_contrato', models.ForeignKey(db_column='id_contrato', on_delete=django.db.models.deletion.CASCADE, to='api.contratos')),
            ],
            options={
                'db_table': 'referencias_personales',
            },
        ),
        migrations.CreateModel(
            name='PersonasInmueble',
            fields=[
                ('id_persona_inmueble', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('parentesco', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(default='OCUPANTE', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_contrato', models.ForeignKey(db_column='id_contrato', on_delete=django.db.models.deletion.CASCADE, to='api.contratos')),
            ],
            options={
                'db_table': 'personas_inmueble',
            },
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_persona', models.CharField(choices=[('FISICA', 'Física'), ('MORAL', 'Moral')], max_length=6)),
                ('nombre', models.CharField(max_length=200)),
                ('rfc', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_domicilio', models.ForeignKey(blank=True, db_column='id_domicilio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.domicilios')),
            ],
            options={
                'db_table': 'personas',
            },
        ),
        migrations.CreateModel(
            name='Ocupantes',
            fields=[
                ('id_ocupante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('parentesco', models.CharField(blank=True, max_length=100, null=True)),
                ('motivo_cambio', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_contrato', models.ForeignKey(db_column='id_contrato', on_delete=django.db.models.deletion.CASCADE, to='api.contratos')),
            ],
            options={
                'db_table': 'ocupantes',
            },
        ),
        migrations.CreateModel(
            name='InformacionLaboral',
            fields=[
                ('id_info_laboral', models.AutoField(primary_key=True, serialize=False)),
                ('ingresos_mensuales', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ocupacion', models.CharField(blank=True, max_length=100, null=True)),
                ('empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('antiguedad', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_domicilio_laboral', models.ForeignKey(blank=True, db_column='id_domicilio_laboral', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domicilio_laboral', to='api.domicilios')),
                ('id_persona', models.ForeignKey(db_column='id_persona', on_delete=django.db.models.deletion.CASCADE, to='api.personas')),
            ],
            options={
                'db_table': 'informacion_laboral',
            },
        ),
        migrations.CreateModel(
            name='InfoConyugal',
            fields=[
                ('id_info_conyugal', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_conyuge', models.CharField(blank=True, max_length=200, null=True)),
                ('regimen_conyugal', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_persona', models.ForeignKey(db_column='id_persona', on_delete=django.db.models.deletion.CASCADE, to='api.personas')),
            ],
            options={
                'db_table': 'info_conyugal',
            },
        ),
        migrations.CreateModel(
            name='Garantias',
            fields=[
                ('id_garantia', models.AutoField(primary_key=True, serialize=False)),
                ('numero_escritura', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_escritura', models.DateField(blank=True, null=True)),
                ('nombre_notario_escritura', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_notaria_escritura', models.CharField(blank=True, max_length=50, null=True)),
                ('ciudad_escritura', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_contrato', models.ForeignKey(db_column='id_contrato', on_delete=django.db.models.deletion.CASCADE, to='api.contratos')),
                ('id_domicilio_garantia', models.ForeignKey(db_column='id_domicilio_garantia', on_delete=django.db.models.deletion.CASCADE, to='api.domicilios')),
            ],
            options={
                'db_table': 'garantias',
            },
        ),
        migrations.CreateModel(
            name='DocumentosLegales',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('ACTA_CONSTITUTIVA', 'Acta Constitutiva'), ('PODER_LEGAL', 'Poder Legal')], max_length=20)),
                ('numero_documento', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_documento', models.DateField(blank=True, null=True)),
                ('nombre_notario', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_notaria', models.CharField(blank=True, max_length=50, null=True)),
                ('ciudad_notaria', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_persona', models.ForeignKey(db_column='id_persona', on_delete=django.db.models.deletion.CASCADE, to='api.personas')),
            ],
            options={
                'db_table': 'documentos_legales',
            },
        ),
        migrations.CreateModel(
            name='DatosEscritura',
            fields=[
                ('id_escritura', models.AutoField(primary_key=True, serialize=False)),
                ('numero_escritura', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_escritura', models.DateField(blank=True, null=True)),
                ('nombre_notario', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_notaria', models.CharField(blank=True, max_length=50, null=True)),
                ('ciudad_escritura', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_garantia', models.ForeignKey(db_column='id_garantia', on_delete=django.db.models.deletion.CASCADE, to='api.garantias')),
            ],
            options={
                'db_table': 'datos_escritura',
            },
        ),
        migrations.CreateModel(
            name='CuentasBancarias',
            fields=[
                ('id_cuenta', models.AutoField(primary_key=True, serialize=False)),
                ('banco', models.CharField(max_length=100)),
                ('beneficiario', models.CharField(max_length=200)),
                ('numero_cuenta', models.CharField(max_length=50)),
                ('clabe', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_persona', models.ForeignKey(db_column='id_persona', on_delete=django.db.models.deletion.CASCADE, to='api.personas')),
            ],
            options={
                'db_table': 'cuentas_bancarias',
            },
        ),
        migrations.AddField(
            model_name='contratos',
            name='id_arrendador',
            field=models.ForeignKey(db_column='id_arrendador', on_delete=django.db.models.deletion.CASCADE, related_name='contratos_arrendador', to='api.personas'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='id_arrendatario',
            field=models.ForeignKey(db_column='id_arrendatario', on_delete=django.db.models.deletion.CASCADE, related_name='contratos_arrendatario', to='api.personas'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='id_cobertura',
            field=models.ForeignKey(blank=True, db_column='id_cobertura', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.coberturas'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='id_inmueble',
            field=models.ForeignKey(db_column='id_inmueble', on_delete=django.db.models.deletion.CASCADE, to='api.inmuebles'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='id_obligado_solidario',
            field=models.ForeignKey(blank=True, db_column='id_obligado_solidario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_obligado', to='api.personas'),
        ),
        migrations.CreateModel(
            name='ArrendadorAnterior',
            fields=[
                ('id_arrendador_anterior', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('domicilio', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_contrato', models.ForeignKey(db_column='id_contrato', on_delete=django.db.models.deletion.CASCADE, to='api.contratos')),
            ],
            options={
                'db_table': 'arrendador_anterior',
            },
        ),
        migrations.CreateModel(
            name='InmueblesUsos',
            fields=[
                ('id_inmueble_uso', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_inmueble', models.ForeignKey(db_column='id_inmueble', on_delete=django.db.models.deletion.CASCADE, to='api.inmuebles')),
                ('id_uso_catalogo', models.ForeignKey(db_column='id_uso_catalogo', on_delete=django.db.models.deletion.CASCADE, to='api.catalogos')),
            ],
            options={
                'db_table': 'inmuebles_usos',
                'unique_together': {('id_inmueble', 'id_uso_catalogo')},
            },
        ),
    ]
