# Generated by Django 4.2.7 on 2025-11-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmuebles',
            name='uso_bodega',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inmuebles',
            name='uso_comercial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inmuebles',
            name='uso_habitacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inmuebles',
            name='uso_oficina',
            field=models.BooleanField(default=False),
        ),
    ]
